---
- hosts: 172.31.10.32
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: install webserver on ubuntu 
    apt:
      name: apache2
      state: present
  - name:  copy myindex file into ansible node side
    copy:
       src: myindexfile
       dest:  /var/www/html/index.html
     
     

